name: Deploy para InfinityFree

on:
  push:
    branches:
      - main  # só faz deploy quando push para main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: "${{ secrets.FTP_HOST }}"
          username: "${{ secrets.FTP_USER }}"
          password: "${{ secrets.FTP_PASS }}"
          local-dir: ./          # raiz do projecto
          server-dir: /htdocs/latest-wasomupfy  # pasta no servidor
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/.env
            **/README.md